import type {
  AgentSentinelState,
  Evidence,
  ExposureFinding,
  GovernancePosture,
  GraphNode,
} from '@agent-sentinel/domain'

const observedAt = '2026-08-14T12:00:00.000Z'

function evidence(id: string, source: string): Evidence {
  return {
    id,
    source,
    sourceObjectId: id,
    observedAt,
    freshness: 'recent',
    confidence: 1,
    summary: `${source} evidence.`,
  }
}

const agents: GraphNode[] = [
  {
    id: 'sales-research-agent',
    kind: 'agent',
    name: 'Sales Research Agent',
    description: 'Creates briefs.',
    environment: 'demo',
    owner: 'Sales AI Platform',
    trust: 'conditional',
    evidenceIds: ['evidence-sales'],
    metadata: { platform: 'Copilot Studio', version: '17', status: 'Published' },
  },
  {
    id: 'hr-policy-agent',
    kind: 'agent',
    name: 'HR Policy Assistant',
    description: 'Answers HR policy questions.',
    environment: 'production',
    owner: 'People & Culture',
    trust: 'trusted',
    evidenceIds: ['evidence-hr-agent-manifest'],
    metadata: { platform: 'Azure OpenAI Service', version: '12', status: 'Published' },
  },
  {
    id: 'code-review-copilot',
    kind: 'agent',
    name: 'Code Review Copilot',
    description: 'Reviews pull requests.',
    environment: 'development',
    owner: 'Engineering Platform',
    trust: 'trusted',
    evidenceIds: ['evidence-cr-agent-manifest'],
    metadata: { platform: 'GitHub Copilot Extensions', version: '3', status: 'Development' },
  },
]

export const testState: AgentSentinelState = {
  snapshot: {
    tenantId: 'test',
    environment: 'test',
    generatedAt: observedAt,
    evidence: [
      evidence('evidence-sales', 'Copilot Studio'),
      evidence('evidence-sales-identity', 'Entra ID'),
      evidence('evidence-hr-agent-manifest', 'Azure OpenAI Service'),
      evidence('evidence-hr-identity-role', 'Microsoft Entra ID'),
      evidence('evidence-hr-data-classification', 'Microsoft Purview'),
      evidence('evidence-hr-mcp-approved', 'Agent Sentinel Trust Catalog'),
      evidence('evidence-cr-agent-manifest', 'GitHub Copilot Extensions'),
      evidence('evidence-cr-identity-role', 'GitHub'),
      evidence('evidence-cr-data-classification', 'Microsoft Purview'),
      evidence('evidence-cr-mcp-approved', 'Agent Sentinel Trust Catalog'),
    ],
    nodes: [
      ...agents,
      {
        id: 'sales-identity',
        kind: 'identity',
        name: 'Sales identity',
        description: 'Sales identity.',
        environment: 'demo',
        trust: 'trusted',
        evidenceIds: ['evidence-sales-identity'],
        metadata: {},
      },
      {
        id: 'hr-agent-identity',
        kind: 'identity',
        name: 'hr-policy-agent-prod',
        description: 'HR identity.',
        environment: 'production',
        owner: 'People & Culture',
        trust: 'trusted',
        evidenceIds: ['evidence-hr-identity-role'],
        metadata: {},
      },
      {
        id: 'hr-knowledge-base',
        kind: 'data',
        name: 'HR Policy Knowledge Base',
        description: 'HR policy data.',
        environment: 'production',
        owner: 'People & Culture',
        trust: 'trusted',
        evidenceIds: ['evidence-hr-data-classification'],
        metadata: {},
      },
      {
        id: 'hr-sharepoint-mcp',
        kind: 'mcp',
        name: 'HR SharePoint MCP',
        description: 'Approved HR MCP.',
        environment: 'production',
        owner: 'People & Culture',
        trust: 'trusted',
        evidenceIds: ['evidence-hr-mcp-approved'],
        metadata: {},
      },
      {
        id: 'cr-agent-identity',
        kind: 'identity',
        name: 'code-review-copilot-app',
        description: 'Code review identity.',
        environment: 'development',
        owner: 'Engineering Platform',
        trust: 'trusted',
        evidenceIds: ['evidence-cr-identity-role'],
        metadata: {},
      },
      {
        id: 'cr-codebase-data',
        kind: 'data',
        name: 'Engineering Codebase',
        description: 'Codebase data.',
        environment: 'development',
        owner: 'Engineering Platform',
        trust: 'trusted',
        evidenceIds: ['evidence-cr-data-classification'],
        metadata: {},
      },
      {
        id: 'cr-github-actions-mcp',
        kind: 'mcp',
        name: 'GitHub Actions MCP',
        description: 'Approved actions MCP.',
        environment: 'development',
        owner: 'Engineering Platform',
        trust: 'trusted',
        evidenceIds: ['evidence-cr-mcp-approved'],
        metadata: {},
      },
    ],
    edges: [
      {
        id: 'edge-sales',
        from: 'sales-research-agent',
        to: 'sales-identity',
        relationship: 'RUNS_AS',
        evidenceIds: ['evidence-sales', 'evidence-sales-identity'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-hr-runs-as',
        from: 'hr-policy-agent',
        to: 'hr-agent-identity',
        relationship: 'RUNS_AS',
        evidenceIds: ['evidence-hr-agent-manifest', 'evidence-hr-identity-role'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-hr-read',
        from: 'hr-agent-identity',
        to: 'hr-knowledge-base',
        relationship: 'CAN_READ',
        evidenceIds: ['evidence-hr-identity-role', 'evidence-hr-data-classification'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-hr-call',
        from: 'hr-policy-agent',
        to: 'hr-sharepoint-mcp',
        relationship: 'CAN_CALL',
        evidenceIds: ['evidence-hr-agent-manifest', 'evidence-hr-mcp-approved'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-cr-runs-as',
        from: 'code-review-copilot',
        to: 'cr-agent-identity',
        relationship: 'RUNS_AS',
        evidenceIds: ['evidence-cr-agent-manifest', 'evidence-cr-identity-role'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-cr-read',
        from: 'cr-agent-identity',
        to: 'cr-codebase-data',
        relationship: 'CAN_READ',
        evidenceIds: ['evidence-cr-identity-role', 'evidence-cr-data-classification'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-cr-call',
        from: 'code-review-copilot',
        to: 'cr-github-actions-mcp',
        relationship: 'CAN_CALL',
        evidenceIds: ['evidence-cr-agent-manifest', 'evidence-cr-mcp-approved'],
        active: true,
        removable: false,
      },
    ],
  },
  findings: [
    {
      id: 'finding-1',
      title: 'Sales exposure',
      summary: 'Sales agent is exposed.',
      severity: 'critical',
      owner: 'Sales AI Platform',
      policyId: 'AS-POL-004',
      detectedAt: observedAt,
      recommendation: 'Contain.',
      path: {
        id: 'path-1',
        nodeIds: ['sales-research-agent', 'sales-identity'],
        edgeIds: ['edge-sales'],
        evidenceIds: ['evidence-sales', 'evidence-sales-identity'],
        riskScore: 82,
        status: 'theoretical',
        factors: {
          reachability: 1,
          exploitability: 0.9,
          businessImpact: 0.9,
          privilege: 0.8,
          dataSensitivity: 0.8,
          activity: 0.8,
          confidence: 0.9,
          compensatingControlDiscount: 0.1,
        },
      },
    },
  ],
  validations: [],
  remediations: [],
}

export const governancePostureFixture: GovernancePosture = {
  policies: [
    {
      id: 'AS-POL-001',
      name: 'Unapproved external transfer or send',
      description: 'External transfers require approval.',
      category: 'Data egress',
      severity: 'critical',
      riskScore: 91,
      status: 'needs-attention',
      openFindings: 2,
      affectedAgents: 2,
      evidenceBasis: 'declared_configuration',
    },
    {
      id: 'AS-POL-002',
      name: 'Overprivileged employee lookup without approval',
      description: 'Sensitive employee fields require approval.',
      category: 'Sensitive data',
      severity: 'high',
      riskScore: 76,
      status: 'compliant',
      openFindings: 0,
      affectedAgents: 0,
      evidenceBasis: 'declared_configuration',
    },
  ],
  summary: {
    totalPolicies: 2,
    compliantPolicies: 1,
    policiesNeedingAttention: 1,
    openFindings: 2,
    affectedAgents: 2,
  },
  latestEvidenceAt: '2026-08-19T09:00:00.000Z',
  sourceMode: 'mock',
  evidenceBasis: 'declared_configuration',
  evaluationCoverage: 'complete',
}

export const salesExposureFinding: ExposureFinding = {
  id: 'finding-1',
  policyId: 'AS-POL-004',
  policyName: 'Data egress without approval',
  severity: 'critical',
  status: 'open',
  riskScore: 82,
  title: 'Sales exposure',
  summary: 'Sales agent is exposed.',
  recommendation: 'Contain.',
  affectedAgentId: 'sales-research-agent',
  affectedAgentName: 'Sales Research Agent',
  declaredTools: [],
  affectedNodeIds: ['sales-research-agent'],
  affectedEdgeIds: ['edge-sales'],
  evidenceIds: ['evidence-sales'],
  evidenceTypes: ['declared_configuration'],
  blastRadiusCount: 2,
  blastRadiusNodeIds: ['sales-research-agent', 'sales-identity'],
  firstSeen: observedAt,
  lastSeen: observedAt,
  sourceMode: 'mock',
  validationStatus: 'theoretical',
  tenantId: 'test',
  snapshotId: 'snap-test',
}
