import type {
  AgentSentinelState,
  Evidence,
  ExposureFinding,
  GovernanceCaseDetail,
  GovernanceQueuePage,
  GovernancePosture,
  GraphNode,
} from '@agent-sentinel/domain'

const observedAt = '2026-08-14T12:00:00.000Z'

function evidence(id: string, source: string): Evidence {
  return {
    id,
    source,
    sourceObjectId: id,
    observedAt,
    freshness: 'recent',
    confidence: 1,
    summary: `${source} evidence.`,
  }
}

const agents: GraphNode[] = [
  {
    id: 'sales-research-agent',
    kind: 'agent',
    name: 'Sales Research Agent',
    description: 'Creates briefs.',
    environment: 'demo',
    owner: 'Sales AI Platform',
    trust: 'conditional',
    evidenceIds: ['evidence-sales'],
    metadata: { platform: 'Copilot Studio', version: '17', status: 'Published' },
  },
  {
    id: 'hr-policy-agent',
    kind: 'agent',
    name: 'HR Policy Assistant',
    description: 'Answers HR policy questions.',
    environment: 'production',
    owner: 'People & Culture',
    trust: 'trusted',
    evidenceIds: ['evidence-hr-agent-manifest'],
    metadata: { platform: 'Azure OpenAI Service', version: '12', status: 'Published' },
  },
  {
    id: 'code-review-copilot',
    kind: 'agent',
    name: 'Code Review Copilot',
    description: 'Reviews pull requests.',
    environment: 'development',
    owner: 'Engineering Platform',
    trust: 'trusted',
    evidenceIds: ['evidence-cr-agent-manifest'],
    metadata: { platform: 'GitHub Copilot Extensions', version: '3', status: 'Development' },
  },
]

export const testState: AgentSentinelState = {
  snapshot: {
    tenantId: 'test',
    environment: 'test',
    generatedAt: observedAt,
    evidence: [
      evidence('evidence-sales', 'Copilot Studio'),
      evidence('evidence-sales-identity', 'Entra ID'),
      evidence('evidence-hr-agent-manifest', 'Azure OpenAI Service'),
      evidence('evidence-hr-identity-role', 'Microsoft Entra ID'),
      evidence('evidence-hr-data-classification', 'Microsoft Purview'),
      evidence('evidence-hr-mcp-approved', 'Agent Sentinel Trust Catalog'),
      evidence('evidence-cr-agent-manifest', 'GitHub Copilot Extensions'),
      evidence('evidence-cr-identity-role', 'GitHub'),
      evidence('evidence-cr-data-classification', 'Microsoft Purview'),
      evidence('evidence-cr-mcp-approved', 'Agent Sentinel Trust Catalog'),
    ],
    nodes: [
      ...agents,
      {
        id: 'sales-identity',
        kind: 'identity',
        name: 'Sales identity',
        description: 'Sales identity.',
        environment: 'demo',
        trust: 'trusted',
        evidenceIds: ['evidence-sales-identity'],
        metadata: {},
      },
      {
        id: 'hr-agent-identity',
        kind: 'identity',
        name: 'hr-policy-agent-prod',
        description: 'HR identity.',
        environment: 'production',
        owner: 'People & Culture',
        trust: 'trusted',
        evidenceIds: ['evidence-hr-identity-role'],
        metadata: {},
      },
      {
        id: 'hr-knowledge-base',
        kind: 'data',
        name: 'HR Policy Knowledge Base',
        description: 'HR policy data.',
        environment: 'production',
        owner: 'People & Culture',
        trust: 'trusted',
        evidenceIds: ['evidence-hr-data-classification'],
        metadata: {},
      },
      {
        id: 'hr-sharepoint-mcp',
        kind: 'mcp',
        name: 'HR SharePoint MCP',
        description: 'Approved HR MCP.',
        environment: 'production',
        owner: 'People & Culture',
        trust: 'trusted',
        evidenceIds: ['evidence-hr-mcp-approved'],
        metadata: {},
      },
      {
        id: 'cr-agent-identity',
        kind: 'identity',
        name: 'code-review-copilot-app',
        description: 'Code review identity.',
        environment: 'development',
        owner: 'Engineering Platform',
        trust: 'trusted',
        evidenceIds: ['evidence-cr-identity-role'],
        metadata: {},
      },
      {
        id: 'cr-codebase-data',
        kind: 'data',
        name: 'Engineering Codebase',
        description: 'Codebase data.',
        environment: 'development',
        owner: 'Engineering Platform',
        trust: 'trusted',
        evidenceIds: ['evidence-cr-data-classification'],
        metadata: {},
      },
      {
        id: 'cr-github-actions-mcp',
        kind: 'mcp',
        name: 'GitHub Actions MCP',
        description: 'Approved actions MCP.',
        environment: 'development',
        owner: 'Engineering Platform',
        trust: 'trusted',
        evidenceIds: ['evidence-cr-mcp-approved'],
        metadata: {},
      },
    ],
    edges: [
      {
        id: 'edge-sales',
        from: 'sales-research-agent',
        to: 'sales-identity',
        relationship: 'RUNS_AS',
        evidenceIds: ['evidence-sales', 'evidence-sales-identity'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-hr-runs-as',
        from: 'hr-policy-agent',
        to: 'hr-agent-identity',
        relationship: 'RUNS_AS',
        evidenceIds: ['evidence-hr-agent-manifest', 'evidence-hr-identity-role'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-hr-read',
        from: 'hr-agent-identity',
        to: 'hr-knowledge-base',
        relationship: 'CAN_READ',
        evidenceIds: ['evidence-hr-identity-role', 'evidence-hr-data-classification'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-hr-call',
        from: 'hr-policy-agent',
        to: 'hr-sharepoint-mcp',
        relationship: 'CAN_CALL',
        evidenceIds: ['evidence-hr-agent-manifest', 'evidence-hr-mcp-approved'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-cr-runs-as',
        from: 'code-review-copilot',
        to: 'cr-agent-identity',
        relationship: 'RUNS_AS',
        evidenceIds: ['evidence-cr-agent-manifest', 'evidence-cr-identity-role'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-cr-read',
        from: 'cr-agent-identity',
        to: 'cr-codebase-data',
        relationship: 'CAN_READ',
        evidenceIds: ['evidence-cr-identity-role', 'evidence-cr-data-classification'],
        active: true,
        removable: false,
      },
      {
        id: 'edge-cr-call',
        from: 'code-review-copilot',
        to: 'cr-github-actions-mcp',
        relationship: 'CAN_CALL',
        evidenceIds: ['evidence-cr-agent-manifest', 'evidence-cr-mcp-approved'],
        active: true,
        removable: false,
      },
    ],
  },
  findings: [
    {
      id: 'finding-1',
      title: 'Sales exposure',
      summary: 'Sales agent is exposed.',
      severity: 'critical',
      owner: 'Sales AI Platform',
      policyId: 'AS-POL-004',
      detectedAt: observedAt,
      recommendation: 'Contain.',
      path: {
        id: 'path-1',
        nodeIds: ['sales-research-agent', 'sales-identity'],
        edgeIds: ['edge-sales'],
        evidenceIds: ['evidence-sales', 'evidence-sales-identity'],
        riskScore: 82,
        status: 'theoretical',
        factors: {
          reachability: 1,
          exploitability: 0.9,
          businessImpact: 0.9,
          privilege: 0.8,
          dataSensitivity: 0.8,
          activity: 0.8,
          confidence: 0.9,
          compensatingControlDiscount: 0.1,
        },
      },
    },
  ],
  validations: [],
  remediations: [],
}

export const governancePostureFixture: GovernancePosture = {
  policies: [
    {
      id: 'AS-POL-001',
      name: 'Unapproved external transfer or send',
      description: 'External transfers require approval.',
      category: 'Data egress',
      severity: 'critical',
      riskScore: 91,
      status: 'needs-attention',
      openFindings: 2,
      affectedAgents: 2,
      evidenceBasis: 'declared_configuration',
    },
    {
      id: 'AS-POL-002',
      name: 'Overprivileged employee lookup without approval',
      description: 'Sensitive employee fields require approval.',
      category: 'Sensitive data',
      severity: 'high',
      riskScore: 76,
      status: 'compliant',
      openFindings: 0,
      affectedAgents: 0,
      evidenceBasis: 'declared_configuration',
    },
  ],
  summary: {
    totalPolicies: 2,
    compliantPolicies: 1,
    policiesNeedingAttention: 1,
    openFindings: 2,
    affectedAgents: 2,
  },
  latestEvidenceAt: '2026-08-19T09:00:00.000Z',
  sourceMode: 'mock',
  evidenceBasis: 'declared_configuration',
  evaluationCoverage: 'complete',
}

export const salesExposureFinding: ExposureFinding = {
  id: 'finding-1',
  policyId: 'AS-POL-004',
  policyName: 'Data egress without approval',
  severity: 'critical',
  status: 'open',
  riskScore: 82,
  title: 'Sales exposure',
  summary: 'Sales agent is exposed.',
  recommendation: 'Contain.',
  affectedAgentId: 'sales-research-agent',
  affectedAgentName: 'Sales Research Agent',
  declaredTools: [],
  affectedNodeIds: ['sales-research-agent'],
  affectedEdgeIds: ['edge-sales'],
  evidenceIds: ['evidence-sales'],
  evidenceTypes: ['declared_configuration'],
  blastRadiusCount: 2,
  blastRadiusNodeIds: ['sales-research-agent', 'sales-identity'],
  firstSeen: observedAt,
  lastSeen: observedAt,
  sourceMode: 'mock',
  validationStatus: 'theoretical',
  tenantId: 'test',
  snapshotId: 'snap-test',
}

export const governanceQueueFixture: GovernanceQueuePage = {
  cases: [
    {
      id: 'gq-001',
      kind: 'finding-review',
      title: '[Mock] Review uncontrolled data egress finding',
      description:
        'Validate the declared external transfer route before proposing any remediation.',
      status: 'open',
      createdByIdentity: 'Morgan Reviewer',
      createdByRole: 'Analyst',
      createdAt: '2026-08-10T09:00:00.000Z',
      lastTransitionAt: '2026-08-10T09:00:00.000Z',
      findingId: 'exposure-as-pol-001-agent-1',
      agentId: 'sales-research-agent',
      policyId: 'AS-POL-001',
      evidenceSnapshotIds: ['mock-snap-001'],
      sourceMode: 'mock',
      writeEnabledAtCreation: false,
    },
    {
      id: 'gq-002',
      kind: 'lifecycle-review',
      title: '[Mock] Confirm HR assistant release controls',
      description:
        'Review the production release gates before the next scheduled lifecycle checkpoint.',
      status: 'in-review',
      createdByIdentity: 'Avery Planner',
      createdByRole: 'Analyst',
      createdAt: '2026-08-19T08:30:00.000Z',
      assigneeIdentity: 'Taylor Analyst',
      lastTransitionAt: '2026-08-20T11:00:00.000Z',
      agentId: 'hr-policy-agent',
      evidenceSnapshotIds: ['mock-snap-002'],
      sourceMode: 'mock',
      writeEnabledAtCreation: false,
    },
    {
      id: 'gq-003',
      kind: 'remediation-proposal',
      title: '[Mock] Approve MCP route containment plan',
      description: 'Approve the containment proposal for the external enrichment route.',
      status: 'pending-approval',
      createdByIdentity: 'Avery Planner',
      createdByRole: 'Analyst',
      createdAt: '2026-08-20T08:00:00.000Z',
      assigneeIdentity: 'Jordan Approver',
      proposerIdentity: 'Avery Planner',
      lastTransitionAt: '2026-08-21T09:30:00.000Z',
      findingId: 'exposure-as-pol-001-agent-1',
      agentId: 'sales-research-agent',
      policyId: 'AS-POL-001',
      evidenceSnapshotIds: ['mock-snap-003'],
      sourceMode: 'mock',
      writeEnabledAtCreation: false,
    },
    {
      id: 'gq-004',
      kind: 'policy-exception',
      title: '[Mock] Close documented exception after control update',
      description:
        'An approved exception can now be closed because the replacement control is documented.',
      status: 'approved',
      createdByIdentity: 'Jordan Approver',
      createdByRole: 'Approver',
      createdAt: '2026-08-18T07:45:00.000Z',
      proposerIdentity: 'Casey Owner',
      lastTransitionAt: '2026-08-22T07:15:00.000Z',
      policyId: 'AS-POL-002',
      evidenceSnapshotIds: ['mock-snap-004'],
      sourceMode: 'mock',
      writeEnabledAtCreation: false,
    },
    {
      id: 'gq-005',
      kind: 'finding-review',
      title: '[Mock] Re-evaluate expired validation case',
      description: 'The queue item exceeded its SLA and requires a fresh analyst review.',
      status: 'expired',
      createdByIdentity: 'Morgan Reviewer',
      createdByRole: 'Analyst',
      createdAt: '2026-08-11T06:15:00.000Z',
      assigneeIdentity: 'Taylor Analyst',
      lastTransitionAt: '2026-08-12T10:00:00.000Z',
      findingId: 'exposure-as-pol-002-agent-2',
      agentId: 'hr-policy-agent',
      policyId: 'AS-POL-002',
      evidenceSnapshotIds: ['mock-snap-005'],
      sourceMode: 'mock',
      writeEnabledAtCreation: false,
    },
  ],
  total: 5,
  summary: {
    total: 5,
    byStatus: {
      open: 1,
      'in-review': 1,
      'pending-approval': 1,
      approved: 1,
      rejected: 0,
      expired: 1,
      closed: 0,
    },
    byKind: {
      'finding-review': 2,
      'remediation-proposal': 1,
      'policy-exception': 1,
      'lifecycle-review': 1,
    },
    overdueCount: 2,
    sourceMode: 'mock',
    persistenceAvailable: true,
  },
}

export const governanceCaseDetailFixture: GovernanceCaseDetail = {
  case: {
    ...governanceQueueFixture.cases[2]!,
    evidenceSnapshotIds: [...governanceQueueFixture.cases[2]!.evidenceSnapshotIds],
  },
  transitions: [
    {
      id: 'transition-gq-003-create',
      caseId: 'gq-003',
      operation: 'create',
      fromStatus: null,
      toStatus: 'open',
      actorIdentity: 'Avery Planner',
      actorRole: 'Analyst',
      actorCapability: 'proposeRemediation',
      timestamp: '2026-08-20T08:00:00.000Z',
      reason: 'Case created in the governance queue.',
      evidenceSnapshotIds: ['mock-snap-003'],
      idempotencyKey: 'seed-gq-003-create',
    },
    {
      id: 'transition-gq-003-pick-up',
      caseId: 'gq-003',
      operation: 'pick-up',
      fromStatus: 'open',
      toStatus: 'in-review',
      actorIdentity: 'Taylor Analyst',
      actorRole: 'Analyst',
      actorCapability: 'validateFinding',
      timestamp: '2026-08-20T13:00:00.000Z',
      reason: 'Analyst review started.',
      evidenceSnapshotIds: ['mock-snap-003'],
      idempotencyKey: 'seed-gq-003-pick-up',
    },
    {
      id: 'transition-gq-003-propose',
      caseId: 'gq-003',
      operation: 'propose',
      fromStatus: 'in-review',
      toStatus: 'pending-approval',
      actorIdentity: 'Avery Planner',
      actorRole: 'Analyst',
      actorCapability: 'proposeRemediation',
      timestamp: '2026-08-21T09:30:00.000Z',
      reason: 'Containment plan submitted for approval.',
      evidenceSnapshotIds: ['mock-snap-003'],
      idempotencyKey: 'seed-gq-003-propose',
    },
  ],
  overdueForAction: false,
}
